version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  run-on-lambda:
    lang: go
    handler: ./run-on-lambda
    image: run-on-lambda:latest
    annotations:
     com.openfaas.federation.gateway: "http://127.0.0.1:8088"
  run-on-k8s:
    lang: go
    handler: ./run-on-k8s
    image: run-on-k8s:latest
